version: '3.8'

services:
  user-frontend:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
