version: '3.8'

services:
  solver-frontend:
    build: .
    ports:
      - "9004:9004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
