version: '3.8'

services:
  transaction-frontend:
    build: .
    ports:
      - "9003:9003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
